 
CREATE TABLE Artist (
artID INT AUTO_INCREMENT NOT NULL,
artName VARCHAR(255) NOT NULL,
CONSTRAINT pk_artist PRIMARY KEY (artID),
CONSTRAINT ck_artist UNIQUE (artName) 
);
 
CREATE TABLE CD (
cdID INT AUTO_INCREMENT NOT NULL,
artID INT NOT NULL,
cdTitle VARCHAR(255) NOT NULL,
cdGenre VARCHAR(100) NOT NULL,
cdTrackno INT NOT NULL,
CONSTRAINT pk_cd PRIMARY KEY (cDID),
CONSTRAINT fk_cd_art FOREIGN KEY (artID) REFERENCES Artist (artID) ON
DELETE CASCADE
);
 
CREATE TABLE Track (
trID INT AUTO_INCREMENT NOT NULL,
cdID INT NOT NULL,
trTitle VARCHAR(255),
trRuntime INT NOT NULL,
CONSTRAINT pk_trID PRIMARY KEY (trID),
CONSTRAINT fk_tr_cd FOREIGN KEY (cdID) REFERENCES CD (cdID) ON
DELETE CASCADE
);
 
